const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 3001;
app.use(helmet());
app.use(cors());
app.use(express.json());
const authRouter = require('./routes/auth');
const aiRouter = require('./routes/ai');
app.use('/api/auth', authRouter);
app.use('/api/ai', aiRouter);
const scrapeRouter = require('./routes/scrape');
const { authMiddleware } = require('./middleware/auth');
app.use('/api/scrape', authMiddleware, scrapeRouter);
const whatsappRouter = require('./routes/whatsapp');
app.use('/api/whatsapp', whatsappRouter);
const emailRouter = require('./routes/email');
app.use('/api/email', emailRouter);
const paymentsRouter = require('./routes/payments');
app.use('/api/payments', paymentsRouter);
app.get('/health', function(req, res) { res.json({ status: 'OK' }); });
app.listen(PORT, function() { console.log('LeadFlow API:' + PORT); });